-- Grant all privileges on the 'fica' database and its objects to a specific user
-- Replace <USER> with the actual username
\c fica;

GRANT ALL PRIVILEGES ON DATABASE fica TO '<USER>';
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO '<USER>';
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO '<USER>';
GRANT ALL PRIVILEGES ON SCHEMA public TO '<USER>';
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO '<USER>';
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO '<USER>';
